customhost = "employee.cl5kzrvha15e.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "limshengyean-employee"
customregion = "us-east-1"